### ISSUE TITLE
Update to reflect changes made to sdks

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex-pfi-exemplar#20]

**Comment by jiyoontbd** [comment]
#21 will only bump web5/dids to 0.2.4 for now since a few PRs are still pending by neal and frank.

once the pending PRs are merged and web5/dids 0.3.x is proven to be compatible with web5/credentials,  https://github.com/TBD54566975/tbdex-pfi-exemplar/issues/24 will target updating all packages to be the latest version.
